In [ ]:
#creating single dimensional array
import numpy as np
n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [ ]:
#creating multi dimensional array
import numpy as np
n2=np.array([[10,34,21,34,23],[23,45,56,23,45]])
n2
type(n2)
print(n2.ndim)

2


In [ ]:
n2

array([[10, 34, 21, 34, 23],
       [23, 45, 56, 23, 45]])

In [ ]:
n2[0] #prints array of index 0

array([10, 34, 21, 34, 23])

In [ ]:
n2[1] #print array of index 1

array([23, 45, 56, 23, 45])

In [ ]:
n2[0,4] #prints 4th element of array of index 0

23

In [ ]:
n2[1,4] #prints 4th element of array of index 1

45

In [ ]:
#checking number of dimensions
import numpy as np
a=np.array(42)
b=np.array([1,2,3,4])
c=np.array([[7,8,9,6],[23,32,54,76]])
d=np.array([[[45,67,54,3],[34,6,65,4]],[[3,5,6,4],[3,5,6,7]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
#extracting of elements
n1[0] #prints element at specified index
n1[1:3] #prints elements from 1 to 3-1 index

array([20, 30])

In [ ]:
import numpy as np
n2=np.array([1,2,3,4,5,6,7,8,9,10])
print(n2[-1:])#prints 10
print(n2[-2:-7])#prints []
print(n2[-7:-2])


[10]
[]
[4 5 6 7 8]


find all the numbers from 1to1000 that have a 11 in them

In [ ]:

for i in range(1,1001):
  if "11" in str(i):
    print(i)

11
110
111
112
113
114
115
116
117
118
119
211
311
411
511
611
711
811
911


In [ ]:
a = np.arange(24) 
b=a.reshape(2,4,3)
c=
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [ ]:
z=np.zeros(5)
print(z)

[0. 0. 0. 0. 0.]


In [ ]:
q=np.arange(2,9)
q

array([2, 3, 4, 5, 6, 7, 8])

In [ ]:
a = np.array([1,2,3,8]) 
b = np.array([10,20,30,40]) 
c = a * b 
print(c)

[ 10  40  90 320]


splitting arrays

In [ ]:
arr = np.array([1, 2, 3, 4, 5,6])
newarr = np.array_split(arr, 3)
print(newarr) 

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
numbers = np.linspace(2, 50, 24, dtype=int)
print(numbers)

[ 2  4  6  8 10 12 14 16 18 20 22 24 27 29 31 33 35 37 39 41 43 45 47 50]


In [ ]:
from numpy import random
x = random.randint(100, size=(3, 5))
print(x) 




[[60 97 86 88 21]
 [87 42 75 63 90]
 [27 94 93 67 57]]


In [ ]:
x = random.choice([3, 5, 7, 9], size=(3, 5))
print(x)

[[9 9 7 3 9]
 [5 9 7 3 3]
 [7 7 3 5 7]]
